language: python
cache: pip
addons:
  chrome: stable
env:
  - USE_DOCKER=no DJANGO_SETTINGS_MODULE=config.settings.test
python:
  - 3.7
install:
  - sudo apt-get install libfftw3-dev libopenblas-dev
  - pip install -q -r requirements/test.txt
script:
  - pytest -v --splinter-webdriver=chrome --splinter-headless=true
notifications:
  email:
    - roettger@tf.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
