version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: topobank_production_django
    depends_on:
      - postgres
      - rabbitmq
      - memcached
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: topobank_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: topobank_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:2015:2015"
      #- "0.0.0.0:80:80"
      #- "0.0.0.0:443:443"

  memcached:
    image: memcached:1.5-alpine

  rabbitmq:
    image: rabbitmq:3.7-alpine

  celeryworker:
    <<: *django
    image: topobank_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: topobank_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: topobank_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
